version: '3'
services:
  nginx: 
    image: nginx:1.17.2
    container_name: production_nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./www/:/var/www
    ports:
      - 8080:443
